---
title: "TAF Manifesto"
author: WGTAFGOV
date: '`r format(Sys.time(), "%a %d %b %Y at %X")`'
output:
  github_document
---

The aim of the Transparent Assessment Framework (TAF) is to assure quality, improve efficiency, and ensure transparency of data and analyses used in the ICES advisory processes.

## Aim / mission statement

### Assuring quality
Assuring quality is a key element of the ICES Advisory Plan (ICES, 2019) and TAF is an essential tool in the overall quality assurance framework. Various quality control check points will be included and documented within TAF.

### Efficiency
ICES experts require a user-friendly framework to archive data, methods, and results used in assessments and advisory products. For recurrent assessments and advice, TAF will ensure that the outputs can be replicated at a future date and also be re-run the following year with minimal changes.

### Transparency
ICES assessments are carried out using various disparate data sources. TAF will ensure transparent input data processing and reproducible assessment methods, while also automating and documenting the outputs which form the evidence base for advisory products. The aim should be that data are available at the highest possible resolution, taking into account confidentiality constraints on these data.

## Historical background

Based on recommendations from the External Review of the Advisory Services (ICES, 2012), and further elaborated by ACOM, Bureau and the Secretariat, a proposal for investment in resources was approved by ICES Council (2015) noting:

  "The (advisory) system should be optimized by freeing them (assessment scientists) from some of their work (shifting update assessment work to the Secretariat). ICES needs to make a more efficient system and the proposed changes are a good investment in the process."

In 2016 an ‘update assessment’ project was launched, resourced by two full-time professional officers and managed jointly by the Head of Advisory support, and the Head of Data and Information. While the brief was to focus on the reproducibility of single stock (recurrent) assessments, data strategy was also considered an integral part of the development. This evolved the initial idea into what was renamed the Transparent Assessment Framework, with the aim of making:

  "an online open resource of ICES stock assessments for each assessment year. All data input and output is fully traceable and versioned"

TAF has made good progress since its initiation in 2016; it has now reached adoption stage. In addition to its initial focus on stock assessment, TAF has provided a framework for:
* Spatial fisheries data quality control and data outputs (WGSFD),
* ICES Fisheries Overviews which will be fully implemented within TAF in 2020,
* Management strategy evaluations (WKNSMSE in 2019),
* Mixed fisheries advice (WGMIXFISH).

As part of the 2019 advice plan, one of the key performance indicators is the adoption of TAF within stock assessments. As of January 2020, there are:
* 50 stocks have been fully implemented in TAF,
* 41 stocks have been partially implemented.

Of the 260 stocks that ICES advises on, the target is to have 200 stocks fully implemented in TAF by 2022.
