---
title: "TAF User Handbook"
author: WGTAFGOV
date: 'built on `r format(Sys.time(), "%a %d %b %Y at %X")`'
output:
  github_document
---

This document is intended for ICES scientists who are developing analyses that will be stored
in the TAF system and uploading data to ICES Databases.  

For users who only are intested in browsing code and results, please go direcly to chapter xxx.

----

## What is TAF

### General description and Manifesto (#1)

### Web application

* loggin in
* linking to GitHub

### TAF Repositories on GitHub

### icesTAF (R package)

----

## Types of repositories according to advice products, linked to issue #13

### Stock assessments

### Other advice products, Fisheries Overviews, other?

### Data products feeding into the other two, f.ex. Survey indices?

### RDBES, maybe for a future update of the handbook?

----

## Users and repositories

### User set up, login, etc.

### Repository setup, who, how, where

----

## Repository structure (link to YouTube tutorial)

### The bootstrap (-> boot) procedure: software
### The bootstrap (-> boot) procedure: data

### Scripts: data
### Scripts: model (-> method)
### Scripts: output
### Scripts: report

----

## TAF scripts

### Reproducible code, relative paths, platform independence

### Writing results into the working folder

### Verifying with `taf = TRUE`

----

## Annotated examples, links to repos

### Assessment (maybe two of different categories or complexity)

### Fisheries Overview, with external data for instance

### Indices from Eggs & Larvae, coming from one of the EGs repositories

### RDBES estimations, in the future

----

## Contacts

 * taf@ices.dk

## Change log and version history of document

date published, change and who prepared it
