name: BuildManifesto
on:
  workflow_dispatch:
  push:
    paths:
      - TAF_Manifesto/TAF_Manifesto.Rmd
      - user_handbooks/user_handbooks.Rmd
      - .github/workflows/taf_manifesto.yml
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up R
      uses: r-lib/actions/setup-r@v2
      with:
        extra-repositories: |
          https://cloud.r-project.org
          https://ices-tools-prod.r-universe.dev
          https://packagemanager.posit.co/cran/__linux__/jammy/latest

    - name: Install R dependencies
      uses: r-lib/actions/setup-r-dependencies@v2
      with:
        extra-packages: |
          any::TAF
          any::rmarkdown

    - name: build manifesto
      run: Rscript -e rmarkdown::render"('taf_manifesto.Rmd', output_file='taf_manifesto.html')"
      working-directory: TAF_Manifesto

    - name: move taf_manifesto.html file to formatted_docs folder
      run: |
        mkdir -p formatted_docs
        mv TAF_Manifesto/taf_manifesto.html formatted_docs/taf_manifesto.html

    - name: build handbook
      run: Rscript -e rmarkdown::render"('user_handbook.Rmd', output_file='user_handbook.html')"
      working-directory: user_handbooks

    - name: move user_handbook.html file to formatted_docs folder
      run: |
        mkdir -p formatted_docs
        mv user_handbooks/user_handbook.html formatted_docs/user_handbook.html

    - name: Git stuff
      run: |
        git config --local user.email "github@ices.dk"
        git config --local user.name "ices-github-bot"
        git status
        git add formatted_docs/taf_manifesto.html
        git add formatted_docs/user_handbook.html
        git commit --allow-empty -m "Push triggered Rmarkdown build"

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
